Leveling
Chimerik/nwn-dotnet pull request #33
Opened 2020-07-26 21:20 UTC by Chimerik

Très artisanal, mais ça reprend globalement ce que je veux faire. Ca marche pas encore tout à fait parce que j'ai pas eu le temps de tester et de corriger mes bêtises.

2020-08-02 14:46 UTC, rgranger requested changes

2020-08-02 14:46 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +
améliorer la lisibilité de cette fonction en la splittant en plus petites fonctions

2020-08-02 14:46 UTC, rgranger commented on Systems/ChatSystem/ChatSystem.cs
> +      return;
le `return;` sur la derniere ligne ne sert toujours à rien

2020-08-02 14:46 UTC, rgranger commented on Systems/ChatSystem/ChatSystem.cs
> +      if (PlayerSystem.Players.TryGetValue(ctx.oSender, out player))
on peut rajouter un "shortcut" : si le player.isAFK est déjà à false, ça ne sert à rien de faire tout le traitement de détection pour le mettre à false.

Pour l'instant ce traitement de détection est léger, mais s'il devient "gros", ça permettra d'améliorer les performances en ne faisant pas le check s'il a déjà été fait suffisamment récemment

2020-08-02 14:46 UTC, rgranger commented on Systems/CommandSystem/CommandDictionnary.cs
> +          name: "bonus roleplay",
il faut que l'attribut "name" de la commande soit identique au la clée du dictionnaire : ici `brp` != `bonus roleplay`.

Car sinon la commande !help ne va pas afficher le bon message : elle va afficher `!bonus roleplay` alors qu'il faut faire `!brp` pour exécuter la commande

2020-08-02 14:46 UTC, rgranger commented on Systems/CommandSystem/CommandDictionnary.cs
> +          name: "bonus roleplay",
Je sais, c'est une petite faiblesse dans mon design de voir écrire 2 fois la meme string plutot qu'une seule fois, mais j'ai pas trouvé de meilleure solution :'(

2020-08-02 14:46 UTC, rgranger commented on Systems/CommandSystem/Commands/SkillMenuCommand.cs
> +        NWScript.DelayCommand(1.0f, () => AutoRefresh(player)); // Pas bon du tout de faire comme ça. Il faudrait ne rafraichir que la ligne correspondant au job actif. C'est envisageable ça ?
Aujourd'hui, non : la fonction `Draw()` dessine la totalité du menu et ne permet pas de redessiner qu'une ligne du menu.

Si on veut que ça soit possible, il va falloir changer pas mal de choses non triviales dans le Menu je pense.

2020-08-02 14:46 UTC, rgranger commented on Systems/PlayerSystem/Player.cs
> +          }
Y'a des trucs qui ressemblent beaucoup à la fonction qui est définie juste au dessus : `CalculateAcquiredSkillPoints`.

Peut etre qu'il y a des choses communes qu'on peut factoriser ?

2020-08-02 14:46 UTC, rgranger commented on Systems/SkillSystem/Skill.cs
> +      public string Nom { get; set; }
name

2020-08-02 14:46 UTC, rgranger commented on Systems/SkillSystem/Skill.cs
> +      private int multiplier;
Pourquoi cet attribut là est-il en minuscule alors que les autres sont en majuscules ?

Il faut essayer d'avoir une convention et de la respecter pour garder une nommage cohérent au sein de l'application.

Moi j'avais plutot suivi cette convention :
* Nom de class en PascalCase
* nom de fonction en PascalCase
* nom d'attribut de class en camelCase

Mais on peut changer si tu en préfères une autre

2020-08-02 14:46 UTC, rgranger commented on Systems/SkillSystem/Skill.cs
> +        NWScript.DelayCommand(1.0f, () => DisplayTimeToNextLevel(oPC));
Du coup elle s'arrête jamais cette fonction?

Btw, je ne suis pas sûre que ça soit une super idée de faire un PostString pour afficher ça :

Si jamais l'utilisateur à placer son Menu au meme endroit que ce message est censé s'afficher, ça va donner un résultat chelou : genre un Menu à laquelle il manque une ligne.

Soit on utilise 1 unique menu par user qui peut choisir de le placer où il veut. Soit on fait un systeme plus compliqué où l'utilisateur peut afficher plusieurs menu simultanément, mais il faut empécher que les menu ne se chevauchent.

Ce qu'on pourrait faire, c'est une sorte de systeme de notifications qui pop les unes apres les autres. Ou sinon juste le truc qui affiche un message sur la tete du joueur (ou SendMessageToPC ? )

2020-08-03 16:09 UTC, Chimerik commented on Systems/SkillSystem/Skill.cs
> +        NWScript.DelayCommand(1.0f, () => DisplayTimeToNextLevel(oPC));
Il me semblait que j'avais mis une variable locale pour que le DelayCommand ne s'exécute que tant que l'utilisateur est sur la page du menu en question. Mais je le retrouve plus. Je le rajouterai en amélioration plus tard, pour que ce soit plus propre.

Pour le reste, OK pour avoir un menu principal qui permette de brancher sur les autres menus. Du coup une commande comme !menu permettrait d'afficher la base du menu et une commande comme !skill permettrait d'arriver directement à la branche des skills ?

Je préférerais qu'on ne passe pas non plus plus trop de temps sur le menu et les PostString, car "un jour" (m'enfin, probablement pas avant longtemps), Beamdog mettra en place un système d'interface utilisateur custom.

Je ne suis pas sur de comprendre pour ton système de notifications. Il faut bien de toute façon que le joueur voit la liste des skills disponibles à l'apprentissage s'afficher et combien de temps il reste pour l'apprentissage de chacun de ces skills ?

Après, effectivement, pour simplifier, on peut se contenter d'afficher le temps restant sur le skill en cours via commande !currentskill + SendMessageToPC(), ce qui accessoirement te permettrait d'éviter d'avoir à te perdre du temps sur un système de rafraîchissement ligne par ligne du menu.

Ça te parait mieux ?

Sachant que de toute façon, si le joueur est connecté et qu'un de ses skills se termine, il reçoit un message le lui indiquant ainsi que l'effet sonore utilisée pour le level up.

2020-08-03 16:10 UTC, Chimerik commented on Systems/SkillSystem/Skill.cs
> +      private int multiplier;
Ça me va. Ça veut dire qu'il faut que je modifier tous mes attributs en maxLevel ? (par exemple)

2020-08-03 16:10 UTC, Chimerik commented on Systems/PlayerSystem/Player.cs
> +          }
Factorisé ! Ça te parait mieux comme ça ?

2020-08-03 16:11 UTC, Chimerik commented on Systems/CommandSystem/Commands/SkillMenuCommand.cs
> +        NWScript.DelayCommand(1.0f, () => AutoRefresh(player)); // Pas bon du tout de faire comme ça. Il faudrait ne rafraichir que la ligne correspondant au job actif. C'est envisageable ça ?
Ok, on peut éventuellement laisser tomber l'histoire du refresh du menu et afficher le temps restant du skill en cours autrement.

2020-08-03 16:12 UTC, Chimerik commented on Systems/ChatSystem/ChatSystem.cs
> +      if (PlayerSystem.Players.TryGetValue(ctx.oSender, out player))
Fait

2020-08-03 16:12 UTC, Chimerik commented on Systems/ChatSystem/ChatSystem.cs
> +      return;
Supprimé

2020-08-03 16:12 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +
Fait. Est-ce que ça te parait mieux ?

2020-08-03 17:59 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +
Oui, ça me parait beaucoup mieux, et toi ça te parait pas mieux ? :)

2020-08-03 18:05 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +    public class Context
Je pense qu'on peut tout mettre ailleurs sauf que la fonction `HandleSkillBookActivate` qui peut rester dans ce fichier.

En effet : si tu as besoin de faire une autre pipeline et un autre context pour un autre handler, tu ne pourras pas l'appeler `Context` car ça sera déjà prix ^^

En gros, il faut soit nommer le context dans ce fichier `SkillsBookContext` pour qu'on sache de quoi il s'agit.
Soit il faut regrouper tout ce qui a rapport au SkillBook dans un autre fichier, et ça donnerait alors `SkillBook.Context` par exemple.

La 2eme solution étant à préfére car si on met plusieurs context / pipeline dans ce fichier, il risque de devenir gros.

2020-08-03 18:07 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +        ActivateItemHandlers.ProcessSkillBookCheckPrerequisteStatsMiddleware,
Typo.

Mais sinon, je trouve les noms un peu long. Si on déplace dans un autre fichier, ça pourrait etre nommé plus simplement :

`SkillBook.CheckStatsMiddleware` ou `SkillBook.CheckRequiredStatsMiddleware`

2020-08-03 18:09 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if(!CheckPlayerPrerequesiteStat("MINATTACKBONUS", ctx.SkillId, ctx.oActivator))
c'est prerequ`i`site non ?

2020-08-03 18:11 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if (result > -1)
Je ne vois pas trop à quoi sert la variable result :

C'est pas plus simple de faire directement : `if (CheckPlayerPrerequesiteFeat("PREREQFEAT1", ctx.SkillId, ctx.oActivator) > -1)` ?

2020-08-03 18:13 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if (result > -1)
A récupérer dans le 2da le nom du Feat/Skill prérequis manquant

2020-08-03 18:15 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +                ctx.oActivator.SendMessage($"Il vous manque un don avant de pouvoir retirer un réel savoir de cet ouvrage");
Je pense qu'on peut simplifier tous ces if imbriqués comme ceci :

```cs
if (
  CheckPlayerPrerequesiteFeat("OrReqFeat0", ctx.SkillId, ctx.oActivator) > -1 &&
  CheckPlayerPrerequesiteFeat("OrReqFeat1", ctx.SkillId, ctx.oActivator) > -1 &&
  CheckPlayerPrerequesiteFeat("OrReqFeat2", ctx.SkillId, ctx.oActivator) > -1 &&
  ...
) {
  ctx.oActivator.SendMessage($"Il vous manque un don avant de pouvoir retirer un réel savoir de cet ouvrage");
}
```

Qu'est-ce que tu en penses?

2020-08-03 18:18 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +                ctx.oActivator.SendMessage($"Il vous manque un don avant de pouvoir retirer un réel savoir de cet ouvrage");
Absolument !

2020-08-03 18:20 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if (result > -1)
🔖 variable result

2020-08-03 18:26 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if (result > -1)
Mais laisse cette variable tranquille, qu'est ce qu'elle t'a fait ? Elle me permet de déterminer le nom du Skill/Feat en défaut

2020-08-03 18:32 UTC, rgranger commented on ScriptHandlers/ActivateItemHandlers.cs
> +      return value;
En c#, on peut renvoyer plusieurs valeurs, sous la forme de "tupple".

Par exemple ici, on pourrait renvoyer un booléen qui indique le succès du parse, et la valeur en meme temps.

Ca permet d'éviter d'avoir une valeur "spéciale" -1.

Ca donnerait qqchose comme :

```cs
private static (bool success, int value) Xxx () {
  return (false, 42);
}

// Utilisation
(bool success, int value) = Xxx()
```

2020-08-03 18:46 UTC, rgranger commented on Systems/PlayerSystem/Player.cs
> +          }
:+1:

2020-08-03 18:48 UTC, rgranger commented on Systems/SkillSystem/Skill.cs
> +      private int multiplier;
oui : acquiredPoints ; name ; description ; currentJob ; pointsToNextLevel ; ...

2020-08-03 19:02 UTC, rgranger commented on Systems/SkillSystem/Skill.cs
> +        NWScript.DelayCommand(1.0f, () => DisplayTimeToNextLevel(oPC));
> Pour le reste, OK pour avoir un menu principal qui permette de brancher sur les autres menus. Du coup une commande comme !menu permettrait d'afficher la base du menu et une commande comme !skill permettrait d'arriver directement à la branche des skills ?

Je ne pense pas avoir compris ^^. Quand on fait !menu on voit un menu qui s'affiche permettant de déplacer le menu. Si on fait ensuite !skills, ca va "effacer" le menu précédent, et afficher à sa place un autre menu.

> Je ne suis pas sur de comprendre pour ton système de notifications. Il faut bien de toute façon que le joueur voit la liste des skills disponibles à l'apprentissage s'afficher et combien de temps il reste pour l'apprentissage de chacun de ces skills ?

Hm, oui, il voit ça dans le menu, non ?

Pour les "notifs" je pensais juste à un message qui s'affiche "Votre job xxx est terminé ! Vous etes maintenant niveau X". Mais peut etre qu'on peut plus simplement envoyer ce message en mode "private message" avec une sorte de bot connecté en permanence juste pour envoyer ces messages aux joueurs. Ca evite d'avoir un systeme trop compliqué.

Mais si on fait un truc trop simple : genre "SendMessageToPC("job fni")" et que le PC est en plein combat, il va probablement ne pas voir que son job est fini et qu'il peut en démarrer un autre.

> Sachant que de toute façon, si le joueur est connecté et qu'un de ses skills se termine, il reçoit un message le lui indiquant ainsi que l'effet sonore utilisée pour le level up.

Ah, oui s'il y a un effet visuel + sonore spécifique, ça peut suffire. Apres faudrait que ça pop aussi quand il reco. Quoique, il peut toujours ouvrir le menu pour voir où en est son skill en cours

2020-08-04 13:34 UTC, Chimerik commented on Systems/SkillSystem/Skill.cs
> +      private int multiplier;
Ok, je le ferai dans une future branche dédiée à ça après merge des branches en cours, histoire d'éviter les conflits

2020-08-04 13:39 UTC, Chimerik commented on Systems/SkillSystem/Skill.cs
> +        NWScript.DelayCommand(1.0f, () => DisplayTimeToNextLevel(oPC));
Oui, ça pop également à la reco. 

De plus, à la reco, si tu n'as pas de skill en cours, on te le signale par un message (je peux ptet également ajouter un effet sonore et visuel pour ce cas. A voir).

2020-08-04 14:14 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +    public class Context
Done

2020-08-04 14:16 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +        ActivateItemHandlers.ProcessSkillBookCheckPrerequisteStatsMiddleware,
Done

2020-08-04 14:17 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +      if(!CheckPlayerPrerequesiteStat("MINATTACKBONUS", ctx.SkillId, ctx.oActivator))
done

2020-08-04 14:20 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +                ctx.oActivator.SendMessage($"Il vous manque un don avant de pouvoir retirer un réel savoir de cet ouvrage");
Done

2020-08-04 14:29 UTC, Chimerik commented on ScriptHandlers/ActivateItemHandlers.cs
> +      return value;
Intéressant. Comment utilise-t-on ça dans le cas :

`if (CheckPlayerRequiredFeat("OrReqFeat0", ctx.skillId, ctx.oActivator) > -1 &&
          CheckPlayerRequiredFeat("OrReqFeat1", ctx.skillId, ctx.oActivator) > -1 &&
          CheckPlayerRequiredFeat("OrReqFeat2", ctx.skillId, ctx.oActivator) > -1 &&
          CheckPlayerRequiredFeat("OrReqFeat3", ctx.skillId, ctx.oActivator) > -1 &&
          CheckPlayerRequiredFeat("OrReqFeat4", ctx.skillId, ctx.oActivator) > -1)`

2020-08-04 18:00 UTC, merged